name: Test and Delpoy

on:
  push:
    branches: [ main ]

jobs:

 test: 
  name: Test 
  run-ons: ubuntu-latest

steps: 
  - uses: action/checkout@v3
  - uses: actions/setup-node@v3
    with:
      node-version: 16.x
    -run: node ci
    -run: npm test